export const IMG_CDN_URL="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
export const GET_RESTUARNT="https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.7040592&lng=77.10249019999999&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
export const resturantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "577210",
        name: "Pablo's Sandwiches",
        uuid: "0da49689-b9b7-4f65-a607-84de7a1e4ece",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "n5ukbce8eaq0vowbeksl",
        cuisines: ["Indian", "Pizzas"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 6.400000095367432,
        slugs: {
          restaurant: "pablo's-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO 212 A SITUATED AT DOMLUR LAYOUT 2ND STAGE 60 FEET ROAD INDIRANAGAR BANAGALORE KARNATAKA INDIA Sarvagna Nagar B B M P East Karnataka 560071",
        locality: "Sarvagna Nagar",
        parentId: 394078,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7188699~p=4~eid=00000189-0899-8c14-1f2e-1c7c00c70441~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "577210",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 6.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "428",
        name: "Biryani Pot",
        uuid: "6db20a8b-dd85-4148-b750-107169f7f826",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "mdipoyzfzsa7n7igskht",
        cuisines: ["North Indian", "Biryani"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 7.5,
        slugs: {
          restaurant: "biryani-pot-madiwala-junction-btm",
          city: "bangalore",
        },
        cityState: "1",
        address: "14th  Cross, 4th link Road Maruthi Nagar Madiwala Bangalore 68",
        locality: "Maruti Nagar",
        parentId: 21798,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 8600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "428",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 7.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "210945",
        name: "Royal Restaurant",
        uuid: "9b33bca4-65e6-4a26-af3e-f47c4476ed4d",
        city: "1",
        area: "Shivajinagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "yicweopn4lzcjlqy4jvq",
        cuisines: ["Chinese", "North Indian", "Tandoor"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "royal-restaurant-central-bangalore-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Broadway Road Police Station, HKP Road, Sulthangunta, Shivajinagar, Bengaluru, Bangalore Urban, Karnataka, India",
        locality: "Sulthangunta",
        parentId: 2896,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 4100,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "210945",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "5938",
        name: "Burger King",
        uuid: "15bfac38-f648-4d1f-8a91-7bbd6f9a4c1e",
        city: "1",
        area: "Shivaji Nagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: "burger-king-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Unit no 111/4, and 8/2, Asha Gallary, Opposite to west side , Commercial Street, Bangalore-  5600001",
        locality: "Tasker Town",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "5938",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "331792",
        name: "Between The Bread",
        uuid: "7198b5d9-e798-4cfb-92a7-6dae39357c93",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "pkp8ofmtnjcedfmvncyw",
        cuisines: [
          "Healthy Food",
          "Beverages",
          "Snacks",
          "American",
          "Continental",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 6.699999809265137,
        slugs: {
          restaurant: "between-the-bread-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "#110, Ground Floor, 18th main, Indiranagar, Bengaluru, Bengaluru Urban, Karnataka, India",
        locality: "HAL 2nd Stage",
        parentId: 43755,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 7600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7213601~p=7~eid=00000189-0899-8c14-1f2e-1c7d00c70743~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "331792",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 6.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "30531",
        name: "Hotel Empire",
        uuid: "fdf6686f-6f39-4a90-8eb0-6dc7abf82643",
        city: "1",
        area: "Brigade Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "qltgnkyywuo5gmnpqzbm",
        cuisines: ["North Indian", "Kebabs", "Biryani"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant: "empire-restaurant-central-bangalore-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Empire SuitesNo.35, Castle Street, Off Brigade Road,Bengaluru, Karnataka 560025",
        locality: "Brigade Road",
        parentId: 475,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹500",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "30531",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "186503",
        name: "Habibi Falafel",
        uuid: "930561d5-3497-4ba7-b7f5-8dcb4fa494de",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "sutdfshrzrxyh4nvtsd7",
        cuisines: ["Middle Eastern", "Lebanese", "Mediterranean", "Arabian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 5.5,
        slugs: {
          restaurant: "habibi-falafel-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address: "Indiranagar, Bengaluru, Karnataka, India",
        locality: "HAL 2nd Stage",
        parentId: 9929,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 6600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6600,
          message: "",
          title: "Delivery Charge",
          amount: "6600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7209634~p=10~eid=00000189-0899-8c14-1f2e-1c7e00c70a49~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "ABOVE ₹800",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "186503",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 5.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.4",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "482672",
        name: "La Pino'z Pizza",
        uuid: "d1911a4e-4b55-484e-9f95-1f5985d04d98",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "glzhq7cgpn4p6ck4t2qs",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 6.800000190734863,
        slugs: {
          restaurant: "la-pino'z-pizza-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Shop No. 2, Building No. 3047, Opp.Kailash Parbat Rastaurant, 80 Feet Road, Hal2Nd Stage, Indira Nagar, Bengaluru ,Karnataka, 560038",
        locality: "HAL 2nd Stage",
        parentId: 4961,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "15% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "482672",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 6.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "196047",
        name: "New Taj Darbar",
        uuid: "94a6fc19-e819-4450-b52f-a96c5a32d565",
        city: "1",
        area: "Shivajinagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "nfieyqgxk1omknxfbluj",
        cuisines: ["Biryani", "Indian", "Chinese", "Tandoor", "Seafood"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "new-taj-darbar-central-bangalore-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address: "New Taj Darbar, Shivaji Nagar, Bengaluru, Karnataka, India",
        locality: "Saint Mary's Church Road",
        parentId: 148190,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "196047",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "568703",
        name: "Baking Bad  - Pizza Delivery",
        uuid: "2e9f1f2a-fee0-4c58-a690-8391f65c7e71",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "6521f722459ec4c4b1f5fbf09b79a23c",
        cuisines: [
          "Pizzas",
          "Burgers",
          "Italian",
          "Desserts",
          "Beverages",
          "American",
          "Continental",
        ],
        tags: [],
        costForTwo: 65000,
        costForTwoString: "₹650 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 5.800000190734863,
        slugs: {
          restaurant: "baking-bad-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 21, 1st floor , CMH Road Hoysala Nagar Indiranagar Bengaluru , Karnataka - 560038",
        locality: "1st Stage",
        parentId: 89,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 6600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6600,
          message: "",
          title: "Delivery Charge",
          amount: "6600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7169432~p=13~eid=00000189-0899-8c14-1f2e-1c7f00c70d77~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.8 kms",
        hasSurge: false,
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "568703",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 5.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "10575",
        name: "Pizza Hut",
        uuid: "92a5861b-2786-4cac-92c2-341cdffd1b27",
        city: "1",
        area: "Shanti Nagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant: "pizza-hut-oshngness-road-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "4/1, O'Shaughnessy Road, Richmond Town, Langford Gardens, Bengaluru, Karnataka 560025",
        locality: "Shanti Nagar",
        parentId: 721,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "10575",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "358613",
        name: "Dr.Gelato",
        uuid: "fdd57954-86ea-4131-a758-fdb6777adf93",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "ectekjxm54dvxetd2zie",
        cuisines: ["Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "dr.gelato-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 26, 1st floor veemee sadhana, 1st main lakhsmipuram, ulsoor, eshwara layout indiranagar banglore karnataka 560008",
        locality: "Lakhsmipuram",
        parentId: 74617,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 6600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6600,
          message: "",
          title: "Delivery Charge",
          amount: "6600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7206849~p=16~eid=00000189-0899-8c14-1f2e-1c8000c71067~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "358613",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "94703",
        name: "Sri Punjabi Dhaba",
        uuid: "244943ac-cb6b-439f-9a09-687af66615b1",
        city: "1",
        area: "BTM Layout",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "i53hrycmcn2oehrojag0",
        cuisines: ["North Indian", "Biryani", "Chinese", "Kebabs"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 7.5,
        slugs: {
          restaurant: "sri-punjabi-dhaba-bangalore-btm",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Opposite 11th Cross 20th Main Rd,beside sri balaji wood Old Madiwala, Cashier Layout,  1st Stage, BTM 1st Stage, Bengaluru, Karnataka 560029",
        locality: "Cashier Layout",
        parentId: 21426,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "94703",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 7.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "333573",
        name: "Chopstick",
        uuid: "5153e599-6085-4c5f-8050-b50c5ad0623d",
        city: "1",
        area: "Jeevan Bima Nagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "zh3pxwfzbvkovh3j7pg4",
        cuisines: [
          "Chinese",
          "Thai",
          "Seafood",
          "Asian",
          "Healthy Food",
          "Beverages",
        ],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "chopstick-indiranagar-indiranagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO.40, KODIHALLI VILLAGE, JEEVAN BHEEMA NAGAR, HAL 2ND STAGE, BANGALORE., Shanthinagara , B.B.M.P East, Karnataka-560075",
        locality: "Kodihalli",
        parentId: 1783,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 8600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7209650~p=19~eid=00000189-0899-8c14-1f2e-1c8100c71345~srvts=1688066427924",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "333573",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "485771",
        name: "Sree Banashankari Donne Biryani",
        uuid: "6c73e264-801e-4a0b-928b-8f91ea32cacb",
        city: "1",
        area: "Basaveshwara Nagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "hrn5r5ghcl7m3piog5iy",
        cuisines: [
          "Biryani",
          "South Indian",
          "Indian",
          "Chinese",
          "Grill",
          "Kebabs",
          "Beverages",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 7.199999809265137,
        slugs: {
          restaurant: "sree-banashankari-donne-biryani-rajajinagar-rajajinagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "#343/344 ground floor 5th main 3rd stage 2nd block basaveshwar Nagar Bengaluru 560079",
        locality: "2nd block",
        parentId: 291485,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 8600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹600",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "485771",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 7.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
  ];